// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/anton-yurchenko/git-release/internal/pkg/interfaces"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/anton-yurchenko/git-release/internal/pkg/repository"

	sync "sync"
)

// Asset is an autogenerated mock type for the Asset type
type Asset struct {
	mock.Mock
}

// SetName provides a mock function with given fields: _a0
func (_m *Asset) SetName(_a0 string) {
	_m.Called(_a0)
}

// SetPath provides a mock function with given fields: _a0
func (_m *Asset) SetPath(_a0 string) {
	_m.Called(_a0)
}

// Upload provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *Asset) Upload(_a0 int64, _a1 repository.Interface, _a2 interfaces.GitHub, _a3 *sync.WaitGroup, _a4 chan string, _a5 chan error) {
	_m.Called(_a0, _a1, _a2, _a3, _a4, _a5)
}
