// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	afero "github.com/spf13/afero"

	mock "github.com/stretchr/testify/mock"
)

// Changelog is an autogenerated mock type for the Changelog type
type Changelog struct {
	mock.Mock
}

// GetBody provides a mock function with given fields:
func (_m *Changelog) GetBody() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetFile provides a mock function with given fields:
func (_m *Changelog) GetFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReadChanges provides a mock function with given fields: _a0
func (_m *Changelog) ReadChanges(_a0 afero.Fs) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(afero.Fs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetFile provides a mock function with given fields: _a0
func (_m *Changelog) SetFile(_a0 string) {
	_m.Called(_a0)
}
