// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/go-github/v78/github"
	mock "github.com/stretchr/testify/mock"
)

// NewGitClient creates a new instance of GitClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitClient {
	mock := &GitClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitClient is an autogenerated mock type for the GitClient type
type GitClient struct {
	mock.Mock
}

type GitClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GitClient) EXPECT() *GitClient_Expecter {
	return &GitClient_Expecter{mock: &_m.Mock}
}

// CreateRef provides a mock function for the type GitClient
func (_mock *GitClient) CreateRef(context1 context.Context, s string, s1 string, createRef github.CreateRef) (*github.Reference, *github.Response, error) {
	ret := _mock.Called(context1, s, s1, createRef)

	if len(ret) == 0 {
		panic("no return value specified for CreateRef")
	}

	var r0 *github.Reference
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, github.CreateRef) (*github.Reference, *github.Response, error)); ok {
		return returnFunc(context1, s, s1, createRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, github.CreateRef) *github.Reference); ok {
		r0 = returnFunc(context1, s, s1, createRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, github.CreateRef) *github.Response); ok {
		r1 = returnFunc(context1, s, s1, createRef)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, github.CreateRef) error); ok {
		r2 = returnFunc(context1, s, s1, createRef)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitClient_CreateRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRef'
type GitClient_CreateRef_Call struct {
	*mock.Call
}

// CreateRef is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - createRef github.CreateRef
func (_e *GitClient_Expecter) CreateRef(context1 any, s any, s1 any, createRef any) *GitClient_CreateRef_Call {
	return &GitClient_CreateRef_Call{Call: _e.mock.On("CreateRef", context1, s, s1, createRef)}
}

func (_c *GitClient_CreateRef_Call) Run(run func(context1 context.Context, s string, s1 string, createRef github.CreateRef)) *GitClient_CreateRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 github.CreateRef
		if args[3] != nil {
			arg3 = args[3].(github.CreateRef)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitClient_CreateRef_Call) Return(reference *github.Reference, response *github.Response, err error) *GitClient_CreateRef_Call {
	_c.Call.Return(reference, response, err)
	return _c
}

func (_c *GitClient_CreateRef_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, createRef github.CreateRef) (*github.Reference, *github.Response, error)) *GitClient_CreateRef_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRef provides a mock function for the type GitClient
func (_mock *GitClient) DeleteRef(context1 context.Context, s string, s1 string, s2 string) (*github.Response, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRef")
	}

	var r0 *github.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.Response, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.Response); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitClient_DeleteRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRef'
type GitClient_DeleteRef_Call struct {
	*mock.Call
}

// DeleteRef is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *GitClient_Expecter) DeleteRef(context1 any, s any, s1 any, s2 any) *GitClient_DeleteRef_Call {
	return &GitClient_DeleteRef_Call{Call: _e.mock.On("DeleteRef", context1, s, s1, s2)}
}

func (_c *GitClient_DeleteRef_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *GitClient_DeleteRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitClient_DeleteRef_Call) Return(response *github.Response, err error) *GitClient_DeleteRef_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *GitClient_DeleteRef_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (*github.Response, error)) *GitClient_DeleteRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetRef provides a mock function for the type GitClient
func (_mock *GitClient) GetRef(context1 context.Context, s string, s1 string, s2 string) (*github.Reference, *github.Response, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for GetRef")
	}

	var r0 *github.Reference
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.Reference, *github.Response, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.Reference); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *github.Response); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(context1, s, s1, s2)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitClient_GetRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRef'
type GitClient_GetRef_Call struct {
	*mock.Call
}

// GetRef is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *GitClient_Expecter) GetRef(context1 any, s any, s1 any, s2 any) *GitClient_GetRef_Call {
	return &GitClient_GetRef_Call{Call: _e.mock.On("GetRef", context1, s, s1, s2)}
}

func (_c *GitClient_GetRef_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *GitClient_GetRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitClient_GetRef_Call) Return(reference *github.Reference, response *github.Response, err error) *GitClient_GetRef_Call {
	_c.Call.Return(reference, response, err)
	return _c
}

func (_c *GitClient_GetRef_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (*github.Reference, *github.Response, error)) *GitClient_GetRef_Call {
	_c.Call.Return(run)
	return _c
}
