package mocks

import (
	asset "github.com/anton-yurchenko/git-release/internal/pkg/asset"
	interfaces "github.com/anton-yurchenko/git-release/internal/pkg/interfaces"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/anton-yurchenko/git-release/internal/pkg/repository"
)

// Release is an autogenerated mock type for the Interface type
type Release struct {
	mock.Mock
}

// EnableDraft provides a mock function with given fields:
func (_m *Release) EnableDraft() {
	_m.Called()
}

// EnablePreRelease provides a mock function with given fields:
func (_m *Release) EnablePreRelease() {
	_m.Called()
}

// GetAssets provides a mock function with given fields:
func (_m *Release) GetAssets() []asset.Asset {
	ret := _m.Called()

	var r0 []asset.Asset
	if rf, ok := ret.Get(0).(func() []asset.Asset); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]asset.Asset)
		}
	}

	return r0
}

// Publish provides a stub function
func (_m *Release) Publish(repository.Interface, interfaces.GitHub, chan string, chan error) error {
	args := _m.Called()

	return args.Error(0)
}

// SetAssets provides a mock function with given fields: _a0
func (_m *Release) SetAssets(_a0 []asset.Asset) {
	_m.Called(_a0)
}
