// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"os"

	"github.com/google/go-github/v78/github"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoriesClient creates a new instance of RepositoriesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoriesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoriesClient {
	mock := &RepositoriesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoriesClient is an autogenerated mock type for the RepositoriesClient type
type RepositoriesClient struct {
	mock.Mock
}

type RepositoriesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoriesClient) EXPECT() *RepositoriesClient_Expecter {
	return &RepositoriesClient_Expecter{mock: &_m.Mock}
}

// CreateRelease provides a mock function for the type RepositoriesClient
func (_mock *RepositoriesClient) CreateRelease(context1 context.Context, s string, s1 string, repositoryRelease *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(context1, s, s1, repositoryRelease)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelease")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(context1, s, s1, repositoryRelease)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.RepositoryRelease) *github.RepositoryRelease); ok {
		r0 = returnFunc(context1, s, s1, repositoryRelease)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.RepositoryRelease) *github.Response); ok {
		r1 = returnFunc(context1, s, s1, repositoryRelease)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.RepositoryRelease) error); ok {
		r2 = returnFunc(context1, s, s1, repositoryRelease)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RepositoriesClient_CreateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelease'
type RepositoriesClient_CreateRelease_Call struct {
	*mock.Call
}

// CreateRelease is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - repositoryRelease *github.RepositoryRelease
func (_e *RepositoriesClient_Expecter) CreateRelease(context1 any, s any, s1 any, repositoryRelease any) *RepositoriesClient_CreateRelease_Call {
	return &RepositoriesClient_CreateRelease_Call{Call: _e.mock.On("CreateRelease", context1, s, s1, repositoryRelease)}
}

func (_c *RepositoriesClient_CreateRelease_Call) Run(run func(context1 context.Context, s string, s1 string, repositoryRelease *github.RepositoryRelease)) *RepositoriesClient_CreateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.RepositoryRelease
		if args[3] != nil {
			arg3 = args[3].(*github.RepositoryRelease)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoriesClient_CreateRelease_Call) Return(repositoryRelease1 *github.RepositoryRelease, response *github.Response, err error) *RepositoriesClient_CreateRelease_Call {
	_c.Call.Return(repositoryRelease1, response, err)
	return _c
}

func (_c *RepositoriesClient_CreateRelease_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, repositoryRelease *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error)) *RepositoriesClient_CreateRelease_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRelease provides a mock function for the type RepositoriesClient
func (_mock *RepositoriesClient) DeleteRelease(context1 context.Context, s string, s1 string, n int64) (*github.Response, error) {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRelease")
	}

	var r0 *github.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*github.Response, error)); ok {
		return returnFunc(context1, s, s1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *github.Response); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(context1, s, s1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoriesClient_DeleteRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRelease'
type RepositoriesClient_DeleteRelease_Call struct {
	*mock.Call
}

// DeleteRelease is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *RepositoriesClient_Expecter) DeleteRelease(context1 any, s any, s1 any, n any) *RepositoriesClient_DeleteRelease_Call {
	return &RepositoriesClient_DeleteRelease_Call{Call: _e.mock.On("DeleteRelease", context1, s, s1, n)}
}

func (_c *RepositoriesClient_DeleteRelease_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *RepositoriesClient_DeleteRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoriesClient_DeleteRelease_Call) Return(response *github.Response, err error) *RepositoriesClient_DeleteRelease_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RepositoriesClient_DeleteRelease_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) (*github.Response, error)) *RepositoriesClient_DeleteRelease_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReleaseAsset provides a mock function for the type RepositoriesClient
func (_mock *RepositoriesClient) DeleteReleaseAsset(context1 context.Context, s string, s1 string, n int64) (*github.Response, error) {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReleaseAsset")
	}

	var r0 *github.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*github.Response, error)); ok {
		return returnFunc(context1, s, s1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *github.Response); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(context1, s, s1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoriesClient_DeleteReleaseAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReleaseAsset'
type RepositoriesClient_DeleteReleaseAsset_Call struct {
	*mock.Call
}

// DeleteReleaseAsset is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *RepositoriesClient_Expecter) DeleteReleaseAsset(context1 any, s any, s1 any, n any) *RepositoriesClient_DeleteReleaseAsset_Call {
	return &RepositoriesClient_DeleteReleaseAsset_Call{Call: _e.mock.On("DeleteReleaseAsset", context1, s, s1, n)}
}

func (_c *RepositoriesClient_DeleteReleaseAsset_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *RepositoriesClient_DeleteReleaseAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoriesClient_DeleteReleaseAsset_Call) Return(response *github.Response, err error) *RepositoriesClient_DeleteReleaseAsset_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *RepositoriesClient_DeleteReleaseAsset_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) (*github.Response, error)) *RepositoriesClient_DeleteReleaseAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseByTag provides a mock function for the type RepositoriesClient
func (_mock *RepositoriesClient) GetReleaseByTag(context1 context.Context, s string, s1 string, s2 string) (*github.RepositoryRelease, *github.Response, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseByTag")
	}

	var r0 *github.RepositoryRelease
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.RepositoryRelease, *github.Response, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.RepositoryRelease); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryRelease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *github.Response); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(context1, s, s1, s2)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RepositoriesClient_GetReleaseByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseByTag'
type RepositoriesClient_GetReleaseByTag_Call struct {
	*mock.Call
}

// GetReleaseByTag is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *RepositoriesClient_Expecter) GetReleaseByTag(context1 any, s any, s1 any, s2 any) *RepositoriesClient_GetReleaseByTag_Call {
	return &RepositoriesClient_GetReleaseByTag_Call{Call: _e.mock.On("GetReleaseByTag", context1, s, s1, s2)}
}

func (_c *RepositoriesClient_GetReleaseByTag_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *RepositoriesClient_GetReleaseByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoriesClient_GetReleaseByTag_Call) Return(repositoryRelease *github.RepositoryRelease, response *github.Response, err error) *RepositoriesClient_GetReleaseByTag_Call {
	_c.Call.Return(repositoryRelease, response, err)
	return _c
}

func (_c *RepositoriesClient_GetReleaseByTag_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (*github.RepositoryRelease, *github.Response, error)) *RepositoriesClient_GetReleaseByTag_Call {
	_c.Call.Return(run)
	return _c
}

// UploadReleaseAsset provides a mock function for the type RepositoriesClient
func (_mock *RepositoriesClient) UploadReleaseAsset(context1 context.Context, s string, s1 string, n int64, uploadOptions *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error) {
	ret := _mock.Called(context1, s, s1, n, uploadOptions, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadReleaseAsset")
	}

	var r0 *github.ReleaseAsset
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) (*github.ReleaseAsset, *github.Response, error)); ok {
		return returnFunc(context1, s, s1, n, uploadOptions, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.ReleaseAsset); ok {
		r0 = returnFunc(context1, s, s1, n, uploadOptions, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.ReleaseAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) *github.Response); ok {
		r1 = returnFunc(context1, s, s1, n, uploadOptions, file)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int64, *github.UploadOptions, *os.File) error); ok {
		r2 = returnFunc(context1, s, s1, n, uploadOptions, file)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RepositoriesClient_UploadReleaseAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadReleaseAsset'
type RepositoriesClient_UploadReleaseAsset_Call struct {
	*mock.Call
}

// UploadReleaseAsset is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
//   - uploadOptions *github.UploadOptions
//   - file *os.File
func (_e *RepositoriesClient_Expecter) UploadReleaseAsset(context1 any, s any, s1 any, n any, uploadOptions any, file any) *RepositoriesClient_UploadReleaseAsset_Call {
	return &RepositoriesClient_UploadReleaseAsset_Call{Call: _e.mock.On("UploadReleaseAsset", context1, s, s1, n, uploadOptions, file)}
}

func (_c *RepositoriesClient_UploadReleaseAsset_Call) Run(run func(context1 context.Context, s string, s1 string, n int64, uploadOptions *github.UploadOptions, file *os.File)) *RepositoriesClient_UploadReleaseAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 *github.UploadOptions
		if args[4] != nil {
			arg4 = args[4].(*github.UploadOptions)
		}
		var arg5 *os.File
		if args[5] != nil {
			arg5 = args[5].(*os.File)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RepositoriesClient_UploadReleaseAsset_Call) Return(releaseAsset *github.ReleaseAsset, response *github.Response, err error) *RepositoriesClient_UploadReleaseAsset_Call {
	_c.Call.Return(releaseAsset, response, err)
	return _c
}

func (_c *RepositoriesClient_UploadReleaseAsset_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64, uploadOptions *github.UploadOptions, file *os.File) (*github.ReleaseAsset, *github.Response, error)) *RepositoriesClient_UploadReleaseAsset_Call {
	_c.Call.Return(run)
	return _c
}
